import os
import json
import requests
import re

def generate_html_report(filename: str, title: str, pages: list[dict]) -> str:
    """
    Generates a professional, interactive HTML documentation site (Javadoc-style).
    
    Args:
        filename: Output filename (e.g., 'docs/index.html').
        title: Project title displayed in the header.
        pages: A list of dicts, each representing a documentation page.
               Format: [{"title": "Overview", "icon": "book", "content": "# Markdown..."}]
    """
    if not filename.endswith('.html'):
        filename += '.html'
    
    # Ensure directory exists
    os.makedirs(os.path.dirname(filename) or '.', exist_ok=True)

    # Serialize pages to JSON for injection into JS
    pages_json = json.dumps(pages)

    html_template = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-dark.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <style>
        body {{ height: 100vh; overflow: hidden; display: flex; flex-direction: column; background-color: #f8f9fa; }}
        .navbar {{ z-index: 1030; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        #main-container {{ display: flex; flex: 1; overflow: hidden; }}
        
        /* Sidebar */
        #sidebar {{ width: 300px; background: white; border-right: 1px solid #dee2e6; overflow-y: auto; padding: 1.5rem; }}
        .nav-link {{ color: #495057; padding: 0.75rem 1rem; border-radius: 8px; margin-bottom: 4px; cursor: pointer; transition: all 0.2s; }}
        .nav-link:hover {{ background-color: #e9ecef; color: #0d6efd; }}
        .nav-link.active {{ background-color: #e7f1ff; color: #0d6efd; font-weight: 600; }}
        .nav-link i {{ margin-right: 10px; }}
        
        /* Content Area */
        #content-area {{ flex: 1; overflow-y: auto; padding: 2rem 4rem; background: #fff; scroll-behavior: smooth; }}
        .markdown-body {{ max-width: 900px; margin: 0 auto; line-height: 1.7; color: #2c3e50; }}
        
        /* Markdown Enhancements */
        h1, h2, h3 {{ color: #2c3e50; margin-top: 1.5em; margin-bottom: 0.5em; }}
        h1 {{ border-bottom: 2px solid #eee; padding-bottom: 0.3em; }}
        pre {{ background: #282c34; padding: 1.2rem; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }}
        code {{ font-family: 'Fira Code', monospace; color: #d63384; }}
        blockquote {{ border-left: 4px solid #0d6efd; padding-left: 1rem; color: #6c757d; background: #f8f9fa; padding: 1rem; border-radius: 4px; }}
        .mermaid {{ background: white; padding: 1rem; border-radius: 8px; text-align: center; border: 1px solid #eee; }}
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <span class="navbar-brand mb-0 h1"><i class="bi bi-code-square me-2"></i>{title}</span>
            <div class="d-flex">
                <div class="input-group">
                    <span class="input-group-text bg-secondary text-white border-0"><i class="bi bi-search"></i></span>
                    <input class="form-control bg-dark text-white border-0" type="search" id="searchBox" placeholder="Filter pages..." aria-label="Search">
                </div>
            </div>
        </div>
    </nav>

    <div id="main-container">
        <div id="sidebar">
            <h6 class="text-muted text-uppercase small mb-3 fw-bold">Documentation</h6>
            <div class="nav flex-column" id="nav-list"></div>
        </div>
        <div id="content-area">
            <div class="markdown-body" id="page-content">
                <div class="text-center text-muted mt-5 pt-5">
                    <h1>Select a page to view details</h1>
                    <p class="lead">Interactive Documentation Generated by AI Agent</p>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
    <script type="module">
        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
        mermaid.initialize({{ startOnLoad: false, theme: 'default' }});
        window.mermaid = mermaid;
    </script>

    <script>
        const pages = {pages_json};
        
        function renderSidebar(items) {{
            const list = document.getElementById('nav-list');
            list.innerHTML = '';
            items.forEach((p, idx) => {{
                const link = document.createElement('div');
                link.className = 'nav-link';
                link.innerHTML = `<i class="bi bi-${{p.icon || 'file-earmark-text'}}"></i>${{p.title}}`;
                link.onclick = () => loadPage(idx);
                list.appendChild(link);
            }});
        }}

        async function loadPage(idx) {{
            // Update Sidebar Active State
            document.querySelectorAll('.nav-link').forEach(l => l.classList.remove('active'));
            document.querySelectorAll('.nav-link')[idx]?.classList.add('active');

            const contentDiv = document.getElementById('page-content');
            const md = pages[idx].content;
            
            // 1. Markdown -> HTML
            contentDiv.innerHTML = marked.parse(md);
            
            // 2. Highlight Code
            hljs.highlightAll();
            
            // 3. Render Mermaid
            const graphs = document.querySelectorAll('.language-mermaid');
            for (const graph of graphs) {{
                const code = graph.innerText;
                const pre = graph.parentElement;
                const div = document.createElement('div');
                div.className = 'mermaid';
                div.textContent = code;
                pre.replaceWith(div);
            }}
            try {{ await window.mermaid.run(); }} catch(e) {{ console.error(e); }}
            
            // Scroll to top
            document.getElementById('content-area').scrollTop = 0;
        }}

        // Search Logic
        document.getElementById('searchBox').addEventListener('input', (e) => {{
            const term = e.target.value.toLowerCase();
            const filtered = pages.map((p, i) => ({{...p, _idx: i}}))
                                  .filter(p => p.title.toLowerCase().includes(term));
            
            const list = document.getElementById('nav-list');
            list.innerHTML = '';
            filtered.forEach(p => {{
                const link = document.createElement('div');
                link.className = 'nav-link';
                link.innerHTML = `<i class="bi bi-${{p.icon || 'file-earmark-text'}}"></i>${{p.title}}`;
                link.onclick = () => loadPage(p._idx);
                list.appendChild(link);
            }});
        }});

        // Init
        renderSidebar(pages);
        if (pages.length > 0) loadPage(0);
    </script>
</body>
</html>
    """

    try:
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(html_template)
        return f"Success: Interactive report generated at {os.path.abspath(filename)}"
    except Exception as e:
        return f"Error creating report: {str(e)}"
    


def create_notion_page(title: str, content: str, notion_token: str, parent_page_id: str) -> str:
    """
    Creates a NEW sub-page inside the parent page.
    Returns the ID of the new page so it can be appended to later.
    """
    if not notion_token or not parent_page_id:
        return "Error: Notion credentials missing."

    url = "https://api.notion.com/v1/pages"
    headers = {
        "Authorization": f"Bearer {notion_token}",
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28"
    }

    all_blocks = parse_markdown_to_blocks(content)
    first_batch = all_blocks[:100]

    payload = {
        "parent": {"page_id": parent_page_id}, 
        "properties": {
            "title": {"title": [{"text": {"content": title}}]}
        },
        "children": first_batch
    }

    try:
        response = requests.post(url, headers=headers, json=payload)
        if response.status_code != 200:
            return f"Error creating page: {response.status_code} - {response.text}"
        
        data = response.json()
        new_page_id = data.get('id')    
        new_page_url = data.get('url')   
        
        if len(all_blocks) > 100:
            remaining = all_blocks[100:]
            _internal_append_blocks(new_page_id, remaining, headers)

        return f"Success: Created new page '{title}'.\nPAGE_ID: {new_page_id}\nURL: {new_page_url}"

    except Exception as e:
        return f"Notion Exception: {str(e)}"

def append_to_notion_page(target_page_id: str, content: str, notion_token: str) -> str:
    """
    Appends content to a SPECIFIC page (using the ID returned by create_notion_page).
    """
    if not notion_token or not target_page_id:
        return "Error: Token or Target Page ID missing."

    headers = {
        "Authorization": f"Bearer {notion_token}",
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28"
    }
    
    blocks = parse_markdown_to_blocks(content)
    return _internal_append_blocks(target_page_id, blocks, headers)

def _internal_append_blocks(page_id: str, blocks: list, headers: dict) -> str:
    """Helper to handle batch appending."""
    url = f"https://api.notion.com/v1/blocks/{page_id}/children"
    batch_size = 100
    total_added = 0
    errors = []

    for i in range(0, len(blocks), batch_size):
        batch = blocks[i : i + batch_size]
        payload = {"children": batch}
        try:
            resp = requests.patch(url, headers=headers, json=payload)
            if resp.status_code == 200:
                total_added += len(batch)
            else:
                errors.append(f"Batch {i} failed: {resp.text}")
        except Exception as e:
            errors.append(str(e))
            
    if errors:
        return f"Partial success: Added {total_added} blocks. Errors: {errors}"
    return f"Success: Appended {total_added} blocks to Page {page_id}."

def parse_markdown_to_blocks(text: str) -> list:
    """
    Parses markdown into Notion Blocks.
    Updates:
    - '- [ ] ' -> To-Do (unchecked)
    - '- [x] ' -> To-Do (checked)
    - '> '     -> Toggle List (useful for hiding answers/details)
    """
    blocks = []
    parts = re.split(r'(```[\s\S]*?```)', text)

    for part in parts:
        if not part.strip(): continue

        if part.startswith("```"):
            # === Code Blocks ===
            content = part.strip()[3:-3]
            lines = content.split('\n', 1)
            language = "plain text"
            code_text = content
            
            if len(lines) > 1:
                first = lines[0].strip().lower()
                if first and first.isalpha(): 
                    language = first
                    code_text = lines[1]
                else:
                    code_text = lines[1] # Handle empty first line case
            
            for chunk in split_text(code_text, 2000):
                blocks.append({
                    "object": "block", "type": "code",
                    "code": {"rich_text": [{"text": {"content": chunk}}], "language": language}
                })
        else:
            # === Text Blocks ===
            lines = part.split('\n')
            for line in lines:
                line = line.strip()
                if not line: continue

                # Headers
                if line.startswith("# "):
                    blocks.append(create_block("heading_1", line[2:]))
                elif line.startswith("## "):
                    blocks.append(create_block("heading_2", line[3:]))
                elif line.startswith("### "):
                    blocks.append(create_block("heading_3", line[4:]))
                
                # Interactive: To-Do List
                elif line.startswith("- [ ] "):
                    blocks.append(create_block("to_do", line[6:], checked=False))
                elif line.startswith("- [x] "):
                    blocks.append(create_block("to_do", line[6:], checked=True))
                
                # Interactive: Toggle List 
                elif line.startswith("> "):
                    blocks.append(create_block("toggle", line[2:]))
                
                # Standard Lists
                elif line.startswith("- ") or line.startswith("* "):
                    blocks.append(create_block("bulleted_list_item", line[2:]))
                
                # Paragraph
                else:
                    blocks.append(create_block("paragraph", line))
    return blocks

def create_block(type_name, text, checked=None):
    """Helper to create standard text-based blocks."""
    content = text[:2000] # Notion limit
    block = {
        "object": "block",
        "type": type_name,
        type_name: {
            "rich_text": [{"type": "text", "text": {"content": content}}]
        }
    }
    # Add checked property for to_do blocks
    if type_name == "to_do" and checked is not None:
        block[type_name]["checked"] = checked
    return block

def split_text(text, length):
    return [text[i:i+length] for i in range(0, len(text), length)]